# Generated by Django 4.2.4 on 2023-08-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('day_of_week', models.CharField(max_length=20)),
                ('time_of_day', models.CharField(max_length=20)),
                ('flying_amount', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
                ('time_with_instructor', models.CharField(max_length=50)),
                ('training_type', models.CharField(max_length=20)),
                ('special_requests', models.CharField(max_length=200)),
            ],
        ),
    ]
