# Generated by Django 4.2.4 on 2023-08-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_category', models.CharField(max_length=20)),
                ('aircraft_availability_day', models.CharField(max_length=20)),
                ('aircraft_start_time', models.CharField(max_length=20)),
                ('aircraft_end_time', models.CharField(max_length=20)),
                ('aircraft_name', models.CharField(max_length=20)),
            ],
        ),
    ]
