# Generated by Django 4.2.4 on 2023-08-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
