# Generated by Django 4.2.4 on 2023-09-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_instructorrequest_alter_flightrequest_training_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrequest',
            name='Instructor_email',
            field=models.EmailField(default='default', max_length=254),
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='training_type',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
