# Generated by Django 4.2.4 on 2023-09-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_instructorrequest_instructor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrequest',
            name='day_available',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
