# Generated by Django 4.2.4 on 2023-09-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_instructorrequest_day_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorrequest',
            old_name='Instructor_day_blocks',
            new_name='duel_blocks',
        ),
        migrations.RenameField(
            model_name='instructorrequest',
            old_name='Instructor_week_blocks',
            new_name='ground_blocks',
        ),
    ]
