# Generated by Django 4.2.4 on 2023-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_instructor_day_blocks_instructorrequest_duel_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='student_blocks',
            field=models.CharField(default='default', max_length=2),
        ),
    ]
