# Generated by Django 4.2.4 on 2023-09-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_flightrequest_student_blocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightrequest',
            old_name='student_blocks',
            new_name='student_ground_blocks',
        ),
    ]
