# Generated by Django 4.2.4 on 2023-09-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_flightrequest_student_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrequest',
            name='instructor_end_time',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='instructor_start_time',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
