# Generated by Django 4.2.4 on 2023-09-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_instructorrequest_instructor_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrequest',
            name='student_end_time',
            field=models.CharField(default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='student_ground_blocks',
            field=models.CharField(default='na', max_length=2),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='student_start_time',
            field=models.CharField(default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='instructorrequest',
            name='Instructor_email',
            field=models.EmailField(default='na', max_length=254),
        ),
        migrations.AlterField(
            model_name='instructorrequest',
            name='day_available',
            field=models.CharField(default='na', max_length=100),
        ),
        migrations.AlterField(
            model_name='instructorrequest',
            name='instructor_end_time',
            field=models.CharField(default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='instructorrequest',
            name='instructor_start_time',
            field=models.CharField(default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='instructorrequest',
            name='training_type',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
