# Generated by Django 4.2.4 on 2023-09-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_flightrequest_time_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='student_duel_blocks',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='student_start_time',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
