# Generated by Django 4.2.4 on 2023-09-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_flightrequest_student_duel_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightrequest',
            name='student_end_time',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='student_start_time',
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='time_request',
            field=models.CharField(default='na', max_length=20),
        ),
    ]
