# Generated by Django 4.2.4 on 2023-09-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_flightrequest_student_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorrequest',
            name='instructor_end_time',
        ),
        migrations.RemoveField(
            model_name='instructorrequest',
            name='instructor_start_time',
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='instructor_times',
            field=models.CharField(default='na', max_length=100),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='time_request',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
