# Generated by Django 4.2.4 on 2023-09-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_instructorrequest_instructor_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightrequest',
            name='flying_amount',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='time_with_instructor',
        ),
    ]
