# Generated by Django 4.2.4 on 2023-09-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_flightrequest_flying_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrequest',
            name='day_of_week',
            field=models.CharField(max_length=100),
        ),
    ]
